const enabled = (value: string | boolean | undefined, fallback: boolean) => {
  if (value === undefined || value === '') return fallback;
  if (typeof value === 'boolean') return value;
  return value.toLowerCase() === 'true';
};

export const launchFeatures = {
  campus: enabled(import.meta.env.VITE_ENABLE_CAMPUS, false),
  marketplace: enabled(import.meta.env.VITE_ENABLE_MARKETPLACE, true),
  examRooms: enabled(import.meta.env.VITE_ENABLE_EXAM_ROOMS, false),
  tutoring: enabled(import.meta.env.VITE_ENABLE_TUTORING, false),
  community: enabled(import.meta.env.VITE_ENABLE_COMMUNITY, false),
  listenAndLearn: enabled(import.meta.env.VITE_ENABLE_LISTEN_AND_LEARN, true),
  talkAndLearn: enabled(import.meta.env.VITE_ENABLE_TALK_AND_LEARN, true),
  notebook: enabled(import.meta.env.VITE_ENABLE_NOTEBOOK, true),
  teacherClasses: enabled(import.meta.env.VITE_ENABLE_TEACHER_CLASSES, true),
  // Soma Paper Studio & Assessment Engine Flags
  paperStudioEnabled: enabled(import.meta.env.VITE_ENABLE_PAPER_STUDIO, true),
  uploadBlueprintEnabled: enabled(import.meta.env.VITE_ENABLE_UPLOAD_BLUEPRINT, true),
  schoolWorkspaceEnabled: enabled(import.meta.env.VITE_ENABLE_SCHOOL_WORKSPACE, true),
  sellerEarningsEnabled: enabled(import.meta.env.VITE_ENABLE_SELLER_EARNINGS, true),
  docxExportEnabled: enabled(import.meta.env.VITE_ENABLE_DOCX_EXPORT, true),
  // Phase 4 Feature Flags — Soma Paper Bank
  paperBankEnabled: enabled(import.meta.env.VITE_ENABLE_PAPER_BANK, true),
  sellerOnboardingEnabled: enabled(import.meta.env.VITE_ENABLE_SELLER_ONBOARDING, true),
  marketplacePurchasesEnabled: enabled(import.meta.env.VITE_ENABLE_MARKETPLACE_PURCHASES, true),

  mpesaPaymentsEnabled: enabled(import.meta.env.VITE_ENABLE_MPESA_PAYMENTS, true),
  sellerWithdrawalsEnabled: enabled(import.meta.env.VITE_ENABLE_SELLER_WITHDRAWALS, true),
  schoolSellerAccountsEnabled: enabled(import.meta.env.VITE_ENABLE_SCHOOL_SELLER_ACCOUNTS, true),
  marketplaceBundlesEnabled: enabled(import.meta.env.VITE_ENABLE_MARKETPLACE_BUNDLES, true),
  marketplaceReviewsEnabled: enabled(import.meta.env.VITE_ENABLE_MARKETPLACE_REVIEWS, true),
  marketplaceModerationEnabled: enabled(import.meta.env.VITE_ENABLE_MARKETPLACE_MODERATION, true),
  schoolBillingEnabled: enabled(import.meta.env.VITE_ENABLE_SCHOOL_BILLING, true),
  districtOversightEnabled: enabled(import.meta.env.VITE_ENABLE_DISTRICT_OVERSIGHT, true),

  // Phase 5 — Assessment Delivery, Marking and Intelligence Flags
  assessmentDeliveryEnabled: enabled(import.meta.env.VITE_ENABLE_ASSESSMENT_DELIVERY, true),
  onlineAssessmentEnabled: enabled(import.meta.env.VITE_ENABLE_ONLINE_ASSESSMENT, true),
  paperAssessmentEnabled: enabled(import.meta.env.VITE_ENABLE_PAPER_ASSESSMENT, true),
  hybridAssessmentEnabled: enabled(import.meta.env.VITE_ENABLE_HYBRID_ASSESSMENT, true),
  objectiveAutoMarkingEnabled: enabled(import.meta.env.VITE_ENABLE_OBJECTIVE_AUTO_MARKING, true),
  teacherMarkingEnabled: enabled(import.meta.env.VITE_ENABLE_TEACHER_MARKING, true),
  answerSheetScanningEnabled: enabled(import.meta.env.VITE_ENABLE_ANSWER_SHEET_SCANNING, true),
  omrScanningEnabled: enabled(import.meta.env.VITE_ENABLE_OMR_SCANNING, true),
  handwritingRecognitionEnabled: enabled(import.meta.env.VITE_ENABLE_HANDWRITING_RECOGNITION, false),
  assessmentAnalyticsEnabled: enabled(import.meta.env.VITE_ENABLE_ASSESSMENT_ANALYTICS, true),
  learnerRevisionRecommendationsEnabled: enabled(import.meta.env.VITE_ENABLE_LEARNER_REVISION_RECOMMENDATIONS, true),
  parentAssessmentReportsEnabled: enabled(import.meta.env.VITE_ENABLE_PARENT_ASSESSMENT_REPORTS, true),
  schoolAssessmentReportsEnabled: enabled(import.meta.env.VITE_ENABLE_SCHOOL_ASSESSMENT_REPORTS, true),
  assessmentCertificatesEnabled: enabled(import.meta.env.VITE_ENABLE_ASSESSMENT_CERTIFICATES, true),

  // Phase 6 — Soma Education Intelligence Flags
  educationIntelligenceEnabled: enabled(import.meta.env.VITE_ENABLE_EDUCATION_INTELLIGENCE, true),
  learnerRiskSignalsEnabled: enabled(import.meta.env.VITE_ENABLE_LEARNER_RISK_SIGNALS, true),
  interventionGroupsEnabled: enabled(import.meta.env.VITE_ENABLE_INTERVENTION_GROUPS, true),
  revisionImpactEnabled: enabled(import.meta.env.VITE_ENABLE_REVISION_IMPACT, true),
  questionQualityIntelligenceEnabled: enabled(import.meta.env.VITE_ENABLE_QUESTION_QUALITY_INTELLIGENCE, true),
  paperQualityScoringEnabled: enabled(import.meta.env.VITE_ENABLE_PAPER_QUALITY_SCORING, true),
  teacherImpactInsightsEnabled: enabled(import.meta.env.VITE_ENABLE_TEACHER_IMPACT_INSIGHTS, false),
  schoolBenchmarkingEnabled: enabled(import.meta.env.VITE_ENABLE_SCHOOL_BENCHMARKING, true),
  anonymousPeerBenchmarkingEnabled: enabled(import.meta.env.VITE_ENABLE_ANONYMOUS_PEER_BENCHMARKING, false),
  predictiveAnalyticsEnabled: enabled(import.meta.env.VITE_ENABLE_PREDICTIVE_ANALYTICS, false),
  leadershipReportsEnabled: enabled(import.meta.env.VITE_ENABLE_LEADERSHIP_REPORTS, true),
  dataQualityMonitoringEnabled: enabled(import.meta.env.VITE_ENABLE_DATA_QUALITY_MONITORING, true),

  // Phase 7 — Soma Content and Curriculum Operating System (Soma Content OS) Flags
  contentOSEnabled: enabled(import.meta.env.VITE_ENABLE_CONTENT_OS, true),
  curriculumExplorerEnabled: enabled(import.meta.env.VITE_ENABLE_CURRICULUM_EXPLORER, true),
  resourceStudioEnabled: enabled(import.meta.env.VITE_ENABLE_RESOURCE_STUDIO, true),
  lessonBuilderEnabled: enabled(import.meta.env.VITE_ENABLE_LESSON_BUILDER, true),
  schoolContentLibraryEnabled: enabled(import.meta.env.VITE_ENABLE_SCHOOL_CONTENT_LIBRARY, true),
  teacherCollaborationEnabled: enabled(import.meta.env.VITE_ENABLE_TEACHER_COLLABORATION, true),
  curriculumVersioningEnabled: enabled(import.meta.env.VITE_ENABLE_CURRICULUM_VERSIONING, true),
  contentLocalizationEnabled: enabled(import.meta.env.VITE_ENABLE_CONTENT_LOCALIZATION, true),
  publisherPortalEnabled: enabled(import.meta.env.VITE_ENABLE_PUBLISHER_PORTAL, false),
  contentLicensingEnabled: enabled(import.meta.env.VITE_ENABLE_CONTENT_LICENSING, true),
  contentMarketplaceEnabled: enabled(import.meta.env.VITE_ENABLE_CONTENT_MARKETPLACE, false),
  contentAPIAccessEnabled: enabled(import.meta.env.VITE_ENABLE_CONTENT_API_ACCESS, false),
  aiContentGenerationEnabled: enabled(import.meta.env.VITE_ENABLE_AI_CONTENT_GENERATION, true),
  contentImportEnabled: enabled(import.meta.env.VITE_ENABLE_CONTENT_IMPORT, true),
  offlineContentPacksEnabled: enabled(import.meta.env.VITE_ENABLE_OFFLINE_CONTENT_PACKS, false),

  // Phase 8 — Soma School Operating System and Institutional Scale (Soma School OS) Flags
  schoolOSEnabled: enabled(import.meta.env.VITE_ENABLE_SCHOOL_OS, true),
  institutionalOnboardingEnabled: enabled(import.meta.env.VITE_ENABLE_INSTITUTIONAL_ONBOARDING, true),
  academicCalendarEnabled: enabled(import.meta.env.VITE_ENABLE_ACADEMIC_CALENDAR, true),
  classManagementEnabled: enabled(import.meta.env.VITE_ENABLE_CLASS_MANAGEMENT, true),
  subjectAllocationEnabled: enabled(import.meta.env.VITE_ENABLE_SUBJECT_ALLOCATION, true),
  parentEngagementEnabled: enabled(import.meta.env.VITE_ENABLE_PARENT_ENGAGEMENT, true),
  revisionProgrammeEnabled: enabled(import.meta.env.VITE_ENABLE_REVISION_PROGRAMME, true),
  curriculumOperationsEnabled: enabled(import.meta.env.VITE_ENABLE_CURRICULUM_OPERATIONS, true),
  multiCampusEnabled: enabled(import.meta.env.VITE_ENABLE_MULTI_CAMPUS, false),

  schoolNetworkEnabled: enabled(import.meta.env.VITE_ENABLE_SCHOOL_NETWORK, false),
  bulkImportEnabled: enabled(import.meta.env.VITE_ENABLE_BULK_IMPORT, true),
  externalIntegrationsEnabled: enabled(import.meta.env.VITE_ENABLE_EXTERNAL_INTEGRATIONS, false),
  institutionAnalyticsEnabled: enabled(import.meta.env.VITE_ENABLE_INSTITUTION_ANALYTICS, false),
  schoolSupportPortalEnabled: enabled(import.meta.env.VITE_ENABLE_SCHOOL_SUPPORT_PORTAL, true),
  offlineSchoolSyncEnabled: enabled(import.meta.env.VITE_ENABLE_OFFLINE_SCHOOL_SYNC, false),

  // Phase 9 — Soma Growth, Distribution and Ecosystem (Soma Growth OS) Flags
  growthOSEnabled: enabled(import.meta.env.VITE_ENABLE_GROWTH_OS, true),
  growthAnalyticsEnabled: enabled(import.meta.env.VITE_ENABLE_GROWTH_ANALYTICS, true),
  teacherReferralEnabled: enabled(import.meta.env.VITE_ENABLE_TEACHER_REFERRAL, true),
  schoolReferralEnabled: enabled(import.meta.env.VITE_ENABLE_SCHOOL_REFERRAL, true),
  ambassadorProgrammeEnabled: enabled(import.meta.env.VITE_ENABLE_AMBASSADOR_PROGRAMME, true),
  creatorProgrammeEnabled: enabled(import.meta.env.VITE_ENABLE_CREATOR_PROGRAMME, true),
  schoolSalesCRMEnabled: enabled(import.meta.env.VITE_ENABLE_SCHOOL_SALES_CRM, true),
  partnerPortalEnabled: enabled(import.meta.env.VITE_ENABLE_PARTNER_PORTAL, false),
  customerSuccessEnabled: enabled(import.meta.env.VITE_ENABLE_CUSTOMER_SUCCESS, true),
  lifecycleMessagingEnabled: enabled(import.meta.env.VITE_ENABLE_LIFECYCLE_MESSAGING, true),
  growthExperimentsEnabled: enabled(import.meta.env.VITE_ENABLE_GROWTH_EXPERIMENTS, false),
  promotionalCreditsEnabled: enabled(import.meta.env.VITE_ENABLE_PROMOTIONAL_CREDITS, true),
  productQualifiedLeadsEnabled: enabled(import.meta.env.VITE_ENABLE_PRODUCT_QUALIFIED_LEADS, true),
  publicResourceDiscoveryEnabled: enabled(import.meta.env.VITE_ENABLE_PUBLIC_RESOURCE_DISCOVERY, true),
  affiliateProgrammeEnabled: enabled(import.meta.env.VITE_ENABLE_AFFILIATE_PROGRAMME, false),
  institutionLeadManagementEnabled: enabled(import.meta.env.VITE_ENABLE_INSTITUTION_LEAD_MANAGEMENT, false),
} as const;