/** Shared editorial requirements for full papers and individual AI variations. */
export const assessmentAnswerGuidance = `Answer-key quality requirements:
- correctAnswer must directly answer every part in the same order as the question. Match the requested number of examples, reasons or methods.
- If extra valid responses are useful, label them "Accept any two of the following" (using the actual requested count), or give the requested number first followed by "Other acceptable answers". Never announce two answers and then present four as the required answer.
- explanation must explain WHY the answer is correct, in clear subject-specific language appropriate to the class. For calculations, show the steps, substitutions and units. For science, explain the causal mechanism. For definitions, clarify the concept with a relevant example when helpful. For MCQ, explain the correct choice and the misconception in a plausible distractor when useful.
- Do not write assessment-purpose commentary such as "This question assesses", "This tests the student's understanding", syllabus alignment, cognitive-level labels, or instructions telling the teacher what to teach. Do not merely repeat the answer or pad a simple answer into a long essay.
- Marking criteria must state the actual knowledge or working that earns each mark, not just "correct definition" or "correct explanation". State how many distinct points earn credit, allow equivalent wording, and do not award duplicate credit for the same point. Criterion marks must add up to the question's marks.
- Every mark must correspond to work explicitly requested in questionText. If a criterion rewards explaining, describing, justifying or showing working, the question must explicitly ask for that work. For "name/list/suggest two", award marks for the two named points only; if explanations are needed, write "Suggest two methods and explain how each works" with a clear mark allocation. Do not add hidden requirements just to reach the requested total marks.
- MULTIPLE_CHOICE is selection-only: correctAnswer is one letter A/B/C/D; markingScheme has exactly one criterion awarding all question marks for selecting that letter. The explanation field is unmarked teaching guidance. If a learner must justify a choice, use STRUCTURED rather than MULTIPLE_CHOICE and explicitly ask for that justification.
- Keep related but different concepts distinct in both answers and explanations. For example, terracing creates level steps on a slope; contour farming follows lines of equal elevation and does not necessarily create steps. Do not merge them with a slash and assign one definition to both.
- Before returning, check consistency between the question, correctAnswer, explanation, option letter and marking criteria. Keep alternatives separate from required responses.
Example of an explanation, not assessment commentary: "Grass roots bind soil particles. The leaves also slow surface runoff, so water carries less soil downhill."`;
