ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS usage_date DATE DEFAULT CURRENT_DATE,
ADD COLUMN IF NOT EXISTS usage_learner INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS usage_revision INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS usage_download INTEGER DEFAULT 0;
