-- SomaAI Creator Marketplace
-- One reviewed submission pipeline, private source storage, secure entitlements,
-- and an immutable 60/40 creator earnings ledger.

create extension if not exists vector;

create or replace function public.is_soma_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) in (
    'admin@soma.app',
    'kariukinjoroge13@gmail.com'
  );
$$;

create table if not exists public.creator_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  account_type text not null default 'TEACHER' check (account_type in ('TEACHER', 'SCHOOL')),
  phone text not null,
  email text,
  county text,
  school_name text,
  subjects text[] not null default '{}',
  grades text[] not null default '{}',
  experience_years integer not null default 0 check (experience_years >= 0),
  payout_method text not null default 'MPESA' check (payout_method in ('MPESA', 'BANK')),
  payout_destination text not null,
  kra_pin text,
  copyright_terms_version text not null default '2026-08-06',
  copyright_accepted_at timestamptz not null default now(),
  status text not null default 'PENDING' check (status in ('PENDING', 'VERIFIED', 'SUSPENDED', 'REJECTED')),
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.creator_materials (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid not null references public.creator_profiles(user_id) on delete cascade,
  title text not null,
  description text not null,
  category text not null check (category in ('EXAM_PAPER', 'REVISION_PAPER', 'NOTES', 'EXAM_GUIDE', 'REVISION_PACK')),
  subject text not null,
  grade text not null,
  curriculum text not null default 'CBC',
  exam_body text,
  year integer,
  price_kes numeric(10,2) not null check (price_kes >= 10 and price_kes <= 5000),
  source_file_path text not null,
  marking_scheme_path text,
  preview_file_path text,
  file_name text not null,
  file_size_bytes bigint not null default 0,
  file_sha256 text,
  version integer not null default 1,
  status text not null default 'DRAFT' check (status in (
    'DRAFT', 'SCREENING', 'EDITORIAL_REVIEW', 'CHANGES_REQUESTED',
    'RIGHTS_EVIDENCE_REQUIRED', 'APPROVED', 'PUBLISHED', 'REJECTED', 'SUSPENDED'
  )),
  screening_status text not null default 'QUEUED' check (screening_status in ('QUEUED', 'PROCESSING', 'PASSED', 'REVIEW_REQUIRED', 'FAILED')),
  quality_score numeric(5,2),
  similarity_score numeric(5,4),
  rights_evidence_required boolean not null default false,
  rights_declaration text not null,
  review_notes text,
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  published_at timestamptz,
  sales_count integer not null default 0,
  rating numeric(3,2) not null default 0,
  rating_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.creator_similarity_reports (
  id uuid primary key default gen_random_uuid(),
  material_id uuid not null references public.creator_materials(id) on delete cascade,
  status text not null check (status in ('PROCESSING', 'PASSED', 'REVIEW_REQUIRED', 'FAILED')),
  maximum_similarity numeric(5,4),
  exact_duplicate boolean not null default false,
  summary text,
  matches jsonb not null default '[]'::jsonb,
  model text,
  created_at timestamptz not null default now()
);

create table if not exists public.creator_material_chunks (
  id bigint generated by default as identity primary key,
  material_id uuid not null references public.creator_materials(id) on delete cascade,
  chunk_index integer not null,
  content text not null,
  embedding vector(768) not null,
  created_at timestamptz not null default now(),
  unique(material_id, chunk_index)
);

create table if not exists public.creator_orders (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid references auth.users(id),
  buyer_phone text not null,
  payment_reference text unique,
  gross_amount_kes numeric(10,2) not null check (gross_amount_kes >= 0),
  status text not null default 'PENDING' check (status in ('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'CHARGEBACK')),
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.creator_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.creator_orders(id) on delete cascade,
  material_id uuid not null references public.creator_materials(id),
  creator_id uuid not null references public.creator_profiles(user_id),
  gross_amount_kes numeric(10,2) not null,
  statutory_adjustments_kes numeric(10,2) not null default 0,
  refund_amount_kes numeric(10,2) not null default 0,
  net_receipts_kes numeric(10,2) not null,
  creator_share_kes numeric(10,2) not null,
  platform_share_kes numeric(10,2) not null,
  creator_share_percent numeric(5,2) not null default 60,
  platform_share_percent numeric(5,2) not null default 40,
  created_at timestamptz not null default now(),
  unique(order_id, material_id)
);

create table if not exists public.material_entitlements (
  id uuid primary key default gen_random_uuid(),
  material_id uuid not null references public.creator_materials(id),
  buyer_id uuid references auth.users(id),
  buyer_phone text not null,
  order_item_id uuid not null references public.creator_order_items(id),
  access_status text not null default 'ACTIVE' check (access_status in ('ACTIVE', 'REVOKED', 'REFUNDED')),
  granted_at timestamptz not null default now(),
  unique(material_id, buyer_phone)
);

create table if not exists public.creator_ledger_entries (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid not null references public.creator_profiles(user_id),
  order_item_id uuid references public.creator_order_items(id),
  payout_id uuid,
  entry_type text not null check (entry_type in ('SALE', 'REFUND', 'CHARGEBACK', 'WITHHOLDING_TAX', 'PAYOUT', 'ADJUSTMENT')),
  amount_kes numeric(10,2) not null,
  state text not null default 'PENDING' check (state in ('PENDING', 'CLEARED', 'SCHEDULED', 'PAID', 'REVERSED')),
  description text not null,
  available_on date,
  created_at timestamptz not null default now()
);

create table if not exists public.creator_payout_batches (
  id uuid primary key default gen_random_uuid(),
  period_start date not null,
  period_end date not null,
  status text not null default 'DRAFT' check (status in ('DRAFT', 'APPROVED', 'PROCESSING', 'PAID', 'FAILED')),
  approved_by uuid references auth.users(id),
  approved_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.creator_payout_items (
  id uuid primary key default gen_random_uuid(),
  batch_id uuid not null references public.creator_payout_batches(id) on delete cascade,
  creator_id uuid not null references public.creator_profiles(user_id),
  gross_earnings_kes numeric(10,2) not null,
  withholding_tax_kes numeric(10,2) not null default 0,
  payout_amount_kes numeric(10,2) not null,
  payment_reference text,
  status text not null default 'SCHEDULED' check (status in ('SCHEDULED', 'PAID', 'FAILED', 'HELD')),
  created_at timestamptz not null default now(),
  unique(batch_id, creator_id)
);

alter table public.creator_ledger_entries
  drop constraint if exists creator_ledger_entries_payout_id_fkey;
alter table public.creator_ledger_entries
  add constraint creator_ledger_entries_payout_id_fkey
  foreign key (payout_id) references public.creator_payout_items(id);

create table if not exists public.creator_referrals (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid not null references public.creator_profiles(user_id) on delete cascade,
  material_id uuid references public.creator_materials(id) on delete cascade,
  code text not null unique,
  click_count integer not null default 0,
  purchase_count integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists creator_materials_public_shelf_idx
  on public.creator_materials(category, published_at desc)
  where status = 'PUBLISHED';
create index if not exists creator_materials_creator_idx
  on public.creator_materials(creator_id, created_at desc);
create index if not exists creator_ledger_creator_idx
  on public.creator_ledger_entries(creator_id, created_at desc);
create index if not exists creator_chunks_embedding_idx
  on public.creator_material_chunks using hnsw (embedding vector_cosine_ops);

alter table public.creator_profiles enable row level security;
alter table public.creator_materials enable row level security;
alter table public.creator_similarity_reports enable row level security;
alter table public.creator_material_chunks enable row level security;
alter table public.creator_orders enable row level security;
alter table public.creator_order_items enable row level security;
alter table public.material_entitlements enable row level security;
alter table public.creator_ledger_entries enable row level security;
alter table public.creator_payout_batches enable row level security;
alter table public.creator_payout_items enable row level security;
alter table public.creator_referrals enable row level security;

create policy "Creators manage own profile" on public.creator_profiles
  for all to authenticated using (auth.uid() = user_id or public.is_soma_admin())
  with check (auth.uid() = user_id or public.is_soma_admin());
create policy "Creators manage own materials" on public.creator_materials
  for all to authenticated using (auth.uid() = creator_id or public.is_soma_admin())
  with check (auth.uid() = creator_id or public.is_soma_admin());
create policy "Public reads published creator materials" on public.creator_materials
  for select to anon using (status = 'PUBLISHED');
create policy "Creators read own similarity reports" on public.creator_similarity_reports
  for select to authenticated using (
    public.is_soma_admin() or exists (
      select 1 from public.creator_materials m where m.id = material_id and m.creator_id = auth.uid()
    )
  );
create policy "Admins manage similarity reports" on public.creator_similarity_reports
  for all to authenticated using (public.is_soma_admin()) with check (public.is_soma_admin());
create policy "Creators read own orders" on public.creator_orders
  for select to authenticated using (buyer_id = auth.uid() or public.is_soma_admin());
create policy "Order parties read items" on public.creator_order_items
  for select to authenticated using (
    creator_id = auth.uid() or public.is_soma_admin() or exists (
      select 1 from public.creator_orders o where o.id = order_id and o.buyer_id = auth.uid()
    )
  );
create policy "Buyers read own entitlements" on public.material_entitlements
  for select to authenticated using (buyer_id = auth.uid() or public.is_soma_admin());
create policy "Creators read own ledger" on public.creator_ledger_entries
  for select to authenticated using (creator_id = auth.uid() or public.is_soma_admin());
create policy "Admins manage payout batches" on public.creator_payout_batches
  for all to authenticated using (public.is_soma_admin()) with check (public.is_soma_admin());
create policy "Creators read payout items" on public.creator_payout_items
  for select to authenticated using (creator_id = auth.uid() or public.is_soma_admin());
create policy "Admins manage payout items" on public.creator_payout_items
  for all to authenticated using (public.is_soma_admin()) with check (public.is_soma_admin());
create policy "Creators manage referrals" on public.creator_referrals
  for all to authenticated using (creator_id = auth.uid() or public.is_soma_admin())
  with check (creator_id = auth.uid() or public.is_soma_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'creator-materials', 'creator-materials', false, 52428800,
  array['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']
)
on conflict (id) do update set public = false, file_size_limit = 52428800;

create policy "Creators upload own source materials" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'creator-materials' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Creators read own source materials" on storage.objects
  for select to authenticated
  using (bucket_id = 'creator-materials' and ((storage.foldername(name))[1] = auth.uid()::text or public.is_soma_admin()));
create policy "Creators update own source materials" on storage.objects
  for update to authenticated
  using (bucket_id = 'creator-materials' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'creator-materials' and (storage.foldername(name))[1] = auth.uid()::text);

create or replace function public.match_creator_material_chunks(
  query_embedding vector(768),
  excluded_material_id uuid,
  match_count integer default 5
) returns table(material_id uuid, content text, similarity float)
language sql stable security definer set search_path = public as $$
  select c.material_id, c.content, (1 - (c.embedding <=> query_embedding))::float as similarity
  from public.creator_material_chunks c
  where c.material_id <> excluded_material_id
  order by c.embedding <=> query_embedding
  limit greatest(1, least(match_count, 20));
$$;

revoke all on function public.match_creator_material_chunks(vector, uuid, integer) from public;
grant execute on function public.match_creator_material_chunks(vector, uuid, integer) to service_role;

create or replace function public.get_creator_earnings_summary()
returns table(
  pending_kes numeric,
  cleared_kes numeric,
  scheduled_kes numeric,
  paid_kes numeric,
  lifetime_sales integer
) language sql stable security invoker as $$
  select
    coalesce(sum(amount_kes) filter (where state = 'PENDING'), 0),
    coalesce(sum(amount_kes) filter (where state = 'CLEARED'), 0),
    coalesce(sum(amount_kes) filter (where state = 'SCHEDULED'), 0),
    coalesce(sum(amount_kes) filter (where state = 'PAID'), 0),
    count(*) filter (where entry_type = 'SALE')::integer
  from public.creator_ledger_entries
  where creator_id = auth.uid();
$$;

create or replace function public.review_creator_material(
  p_material_id uuid,
  p_decision text,
  p_notes text default null
) returns public.creator_materials
language plpgsql security definer set search_path = public as $$
declare
  updated public.creator_materials;
  next_status text;
begin
  if not public.is_soma_admin() then raise exception 'Admin access required'; end if;
  next_status := case upper(p_decision)
    when 'APPROVE' then 'APPROVED'
    when 'PUBLISH' then 'PUBLISHED'
    when 'REQUEST_CHANGES' then 'CHANGES_REQUESTED'
    when 'REQUEST_RIGHTS' then 'RIGHTS_EVIDENCE_REQUIRED'
    when 'REJECT' then 'REJECTED'
    else null
  end;
  if next_status is null then raise exception 'Unsupported review decision'; end if;

  update public.creator_materials
  set status = next_status,
      review_notes = nullif(trim(p_notes), ''),
      reviewed_by = auth.uid(), reviewed_at = now(),
      published_at = case when next_status = 'PUBLISHED' then now() else published_at end,
      updated_at = now()
  where id = p_material_id
  returning * into updated;
  return updated;
end;
$$;

revoke all on function public.review_creator_material(uuid, text, text) from public;
grant execute on function public.review_creator_material(uuid, text, text) to authenticated;

create or replace function public.record_creator_material_sale(
  p_material_id uuid,
  p_buyer_id uuid,
  p_buyer_phone text,
  p_payment_reference text,
  p_gross_amount_kes numeric,
  p_statutory_adjustments_kes numeric default 0
) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  material public.creator_materials;
  order_id uuid;
  item_id uuid;
  net numeric(10,2);
  creator_share numeric(10,2);
begin
  if auth.role() <> 'service_role' then raise exception 'Payment service access required'; end if;
  select * into material from public.creator_materials where id = p_material_id and status = 'PUBLISHED';
  if material.id is null then raise exception 'Published material not found'; end if;
  if p_gross_amount_kes <> material.price_kes then raise exception 'Payment amount does not match listing price'; end if;
  net := greatest(0, p_gross_amount_kes - greatest(0, p_statutory_adjustments_kes));
  creator_share := round(net * 0.60, 2);

  insert into public.creator_orders(buyer_id, buyer_phone, payment_reference, gross_amount_kes, status, paid_at)
  values(p_buyer_id, p_buyer_phone, p_payment_reference, p_gross_amount_kes, 'PAID', now())
  returning id into order_id;
  insert into public.creator_order_items(
    order_id, material_id, creator_id, gross_amount_kes, statutory_adjustments_kes,
    net_receipts_kes, creator_share_kes, platform_share_kes
  ) values(
    order_id, material.id, material.creator_id, p_gross_amount_kes, p_statutory_adjustments_kes,
    net, creator_share, net - creator_share
  ) returning id into item_id;
  insert into public.material_entitlements(material_id, buyer_id, buyer_phone, order_item_id)
  values(material.id, p_buyer_id, p_buyer_phone, item_id)
  on conflict(material_id, buyer_phone) do update set access_status = 'ACTIVE', order_item_id = excluded.order_item_id;
  insert into public.creator_ledger_entries(creator_id, order_item_id, entry_type, amount_kes, state, description, available_on)
  values(material.creator_id, item_id, 'SALE', creator_share, 'PENDING', '60% creator share for ' || material.title, current_date + 14);
  update public.creator_materials set sales_count = sales_count + 1 where id = material.id;
  return order_id;
end;
$$;

revoke all on function public.record_creator_material_sale(uuid, uuid, text, text, numeric, numeric) from public;
grant execute on function public.record_creator_material_sale(uuid, uuid, text, text, numeric, numeric) to service_role;

grant select on public.creator_materials to anon, authenticated;
grant select, insert, update on public.creator_profiles, public.creator_materials, public.creator_referrals to authenticated;
grant select on public.creator_similarity_reports, public.creator_orders, public.creator_order_items,
  public.material_entitlements, public.creator_ledger_entries, public.creator_payout_batches,
  public.creator_payout_items to authenticated;
grant select, insert, update on public.creator_similarity_reports to service_role;
grant select, insert, update, delete on public.creator_material_chunks to service_role;

comment on table public.creator_ledger_entries is 'Immutable creator earnings ledger. Client roles have SELECT only; sale and payout entries are server-generated.';
comment on column public.creator_materials.similarity_score is 'Screening signal only. Similarity does not establish copyright infringement.';
